# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ModuleArgs', 'Module']

@pulumi.input_type
class ModuleArgs:
    def __init__(__self__, *,
                 source: _builtins.str,
                 inputs: pulumi.Input[Optional[Mapping[str, Any]]] = None,
                 version: Optional[_builtins.str] = None):
        """
        The set of arguments for constructing a Module resource.

        :param _builtins.str source: The module source address (a registry reference, URL, or local path).
        :param pulumi.Input[Mapping[str, Any]] inputs: The module's input variables, keyed by variable name.
        :param _builtins.str version: An optional version constraint, used when source is a registry module reference.
        """
        pulumi.set(__self__, "source", source)
        if inputs is not None:
            pulumi.set(__self__, "inputs", inputs)
        if version is not None:
            pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter
    def source(self) -> _builtins.str:
        """
        The module source address (a registry reference, URL, or local path).
        """
        return pulumi.get(self, "source")

    @source.setter
    def source(self, value: _builtins.str):
        pulumi.set(self, "source", value)

    @_builtins.property
    @pulumi.getter
    def inputs(self) -> pulumi.Input[Optional[Mapping[str, Any]]]:
        """
        The module's input variables, keyed by variable name.
        """
        return pulumi.get(self, "inputs")

    @inputs.setter
    def inputs(self, value: pulumi.Input[Optional[Mapping[str, Any]]]):
        pulumi.set(self, "inputs", value)

    @_builtins.property
    @pulumi.getter
    def version(self) -> Optional[_builtins.str]:
        """
        An optional version constraint, used when source is a registry module reference.
        """
        return pulumi.get(self, "version")

    @version.setter
    def version(self, value: Optional[_builtins.str]):
        pulumi.set(self, "version", value)


@pulumi.type_token("hcl:index:Module")
class Module(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 inputs: pulumi.Input[Optional[Mapping[str, Any]]] = None,
                 source: Optional[_builtins.str] = None,
                 version: Optional[_builtins.str] = None,
                 __props__=None):
        """
        A Terraform/OpenTofu module instantiated as a component resource.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Mapping[str, Any]] inputs: The module's input variables, keyed by variable name.
        :param _builtins.str source: The module source address (a registry reference, URL, or local path).
        :param _builtins.str version: An optional version constraint, used when source is a registry module reference.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ModuleArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        A Terraform/OpenTofu module instantiated as a component resource.

        :param str resource_name: The name of the resource.
        :param ModuleArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ModuleArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 inputs: pulumi.Input[Optional[Mapping[str, Any]]] = None,
                 source: Optional[_builtins.str] = None,
                 version: Optional[_builtins.str] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ModuleArgs.__new__(ModuleArgs)

            __props__.__dict__["inputs"] = inputs
            if source is None and not opts.urn:
                raise TypeError("Missing required property 'source'")
            __props__.__dict__["source"] = source
            __props__.__dict__["version"] = version
            __props__.__dict__["outputs"] = None
        super(Module, __self__).__init__(
            'hcl:index:Module',
            resource_name,
            __props__,
            opts,
            remote=True)

    @_builtins.property
    @pulumi.getter
    def inputs(self) -> pulumi.Output[Optional[Mapping[str, Any]]]:
        """
        The module's input variables, keyed by variable name.
        """
        return pulumi.get(self, "inputs")

    @_builtins.property
    @pulumi.getter
    def outputs(self) -> pulumi.Output[Mapping[str, Any]]:
        """
        The module's output values, keyed by output name.
        """
        return pulumi.get(self, "outputs")

    @_builtins.property
    @pulumi.getter
    def source(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The module source address (a registry reference, URL, or local path).
        """
        return pulumi.get(self, "source")

    @_builtins.property
    @pulumi.getter
    def version(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        An optional version constraint, used when source is a registry module reference.
        """
        return pulumi.get(self, "version")

