version: 2

builds:
  - id: pulumi-language-hcl
    binary: pulumi-language-hcl
    main: ./cmd/pulumi-language-hcl
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -w -s -X github.com/pulumi-labs/pulumi-hcl/pkg/version.version={{.Tag}}

  - id: pulumi-converter-hcl
    binary: pulumi-converter-hcl
    main: ./cmd/pulumi-converter-hcl
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -w -s -X github.com/pulumi-labs/pulumi-hcl/pkg/version.version={{.Tag}}

archives:
  - id: pulumi-language-hcl
    builds:
      - pulumi-language-hcl
    name_template: "pulumi-language-hcl-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
  - id: pulumi-converter-hcl
    builds:
      - pulumi-converter-hcl
    name_template: "pulumi-converter-hcl-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"

snapshot:
  version_template: "{{ .Tag }}-SNAPSHOT"

checksum:
  name_template: 'checksums.txt'

release:
  mode: keep-existing
