// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Hcl
{
    /// <summary>
    /// A Terraform/OpenTofu module instantiated as a component resource.
    /// </summary>
    [HclResourceType("hcl:index:Module")]
    public partial class Module : global::Pulumi.ComponentResource
    {
        /// <summary>
        /// The module's input variables, keyed by variable name.
        /// </summary>
        [Output("inputs")]
        public Output<ImmutableDictionary<string, object>?> Inputs { get; private set; } = null!;

        /// <summary>
        /// The module's output values, keyed by output name.
        /// </summary>
        [Output("outputs")]
        public Output<ImmutableDictionary<string, object>> Outputs { get; private set; } = null!;

        /// <summary>
        /// The module source address (a registry reference, URL, or local path).
        /// </summary>
        [Output("source")]
        public Output<string?> Source { get; private set; } = null!;

        /// <summary>
        /// An optional version constraint, used when source is a registry module reference.
        /// </summary>
        [Output("version")]
        public Output<string?> Version { get; private set; } = null!;


        /// <summary>
        /// Create a Module resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Module(string name, ModuleArgs args, ComponentResourceOptions? options = null)
            : base("hcl:index:Module", name, args ?? new ModuleArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class ModuleArgs : global::Pulumi.ResourceArgs
    {
        [Input("inputs")]
        private InputMap<object>? _inputs;

        /// <summary>
        /// The module's input variables, keyed by variable name.
        /// </summary>
        public InputMap<object> Inputs
        {
            get => _inputs ?? (_inputs = new InputMap<object>());
            set => _inputs = value;
        }

        /// <summary>
        /// The module source address (a registry reference, URL, or local path).
        /// </summary>
        [Input("source", required: true)]
        public string Source { get; set; } = null!;

        /// <summary>
        /// An optional version constraint, used when source is a registry module reference.
        /// </summary>
        [Input("version")]
        public string? Version { get; set; }

        public ModuleArgs()
        {
        }
        public static new ModuleArgs Empty => new ModuleArgs();
    }
}
