// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package hcl

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-hcl/sdk/go/hcl/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A Terraform/OpenTofu module instantiated as a component resource.
type Module struct {
	pulumi.ResourceState

	// The module's input variables, keyed by variable name.
	Inputs pulumi.MapOutput `pulumi:"inputs"`
	// The module's output values, keyed by output name.
	Outputs pulumi.MapOutput `pulumi:"outputs"`
	// The module source address (a registry reference, URL, or local path).
	Source pulumi.StringPtrOutput `pulumi:"source"`
	// An optional version constraint, used when source is a registry module reference.
	Version pulumi.StringPtrOutput `pulumi:"version"`
}

// NewModule registers a new resource with the given unique name, arguments, and options.
func NewModule(ctx *pulumi.Context,
	name string, args *ModuleArgs, opts ...pulumi.ResourceOption) (*Module, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Module
	err := ctx.RegisterRemoteComponentResource("hcl:index:Module", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type moduleArgs struct {
	// The module's input variables, keyed by variable name.
	Inputs map[string]interface{} `pulumi:"inputs"`
	// The module source address (a registry reference, URL, or local path).
	Source string `pulumi:"source"`
	// An optional version constraint, used when source is a registry module reference.
	Version *string `pulumi:"version"`
}

// The set of arguments for constructing a Module resource.
type ModuleArgs struct {
	// The module's input variables, keyed by variable name.
	Inputs pulumi.MapInput
	// The module source address (a registry reference, URL, or local path).
	Source string
	// An optional version constraint, used when source is a registry module reference.
	Version *string
}

func (ModuleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*moduleArgs)(nil)).Elem()
}

type ModuleInput interface {
	pulumi.Input

	ToModuleOutput() ModuleOutput
	ToModuleOutputWithContext(ctx context.Context) ModuleOutput
}

func (*Module) ElementType() reflect.Type {
	return reflect.TypeOf((**Module)(nil)).Elem()
}

func (i *Module) ToModuleOutput() ModuleOutput {
	return i.ToModuleOutputWithContext(context.Background())
}

func (i *Module) ToModuleOutputWithContext(ctx context.Context) ModuleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ModuleOutput)
}

type ModuleOutput struct{ *pulumi.OutputState }

func (ModuleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Module)(nil)).Elem()
}

func (o ModuleOutput) ToModuleOutput() ModuleOutput {
	return o
}

func (o ModuleOutput) ToModuleOutputWithContext(ctx context.Context) ModuleOutput {
	return o
}

// The module's input variables, keyed by variable name.
func (o ModuleOutput) Inputs() pulumi.MapOutput {
	return o.ApplyT(func(v *Module) pulumi.MapOutput { return v.Inputs }).(pulumi.MapOutput)
}

// The module's output values, keyed by output name.
func (o ModuleOutput) Outputs() pulumi.MapOutput {
	return o.ApplyT(func(v *Module) pulumi.MapOutput { return v.Outputs }).(pulumi.MapOutput)
}

// The module source address (a registry reference, URL, or local path).
func (o ModuleOutput) Source() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Module) pulumi.StringPtrOutput { return v.Source }).(pulumi.StringPtrOutput)
}

// An optional version constraint, used when source is a registry module reference.
func (o ModuleOutput) Version() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Module) pulumi.StringPtrOutput { return v.Version }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ModuleInput)(nil)).Elem(), &Module{})
	pulumi.RegisterOutputType(ModuleOutput{})
}
