// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.hcl;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Object;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ModuleArgs extends com.pulumi.resources.ResourceArgs {

    public static final ModuleArgs Empty = new ModuleArgs();

    /**
     * The module&#39;s input variables, keyed by variable name.
     * 
     */
    @Import(name="inputs")
    private @Nullable Output<Map<String,Object>> inputs;

    /**
     * @return The module&#39;s input variables, keyed by variable name.
     * 
     */
    public Optional<Output<Map<String,Object>>> inputs() {
        return Optional.ofNullable(this.inputs);
    }

    /**
     * The module source address (a registry reference, URL, or local path).
     * 
     */
    @Import(name="source", required=true)
    private String source;

    /**
     * @return The module source address (a registry reference, URL, or local path).
     * 
     */
    public String source() {
        return this.source;
    }

    /**
     * An optional version constraint, used when source is a registry module reference.
     * 
     */
    @Import(name="version")
    private @Nullable String version;

    /**
     * @return An optional version constraint, used when source is a registry module reference.
     * 
     */
    public Optional<String> version() {
        return Optional.ofNullable(this.version);
    }

    private ModuleArgs() {}

    private ModuleArgs(ModuleArgs $) {
        this.inputs = $.inputs;
        this.source = $.source;
        this.version = $.version;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ModuleArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ModuleArgs $;

        public Builder() {
            $ = new ModuleArgs();
        }

        public Builder(ModuleArgs defaults) {
            $ = new ModuleArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param inputs The module&#39;s input variables, keyed by variable name.
         * 
         * @return builder
         * 
         */
        public Builder inputs(@Nullable Output<Map<String,Object>> inputs) {
            $.inputs = inputs;
            return this;
        }

        /**
         * @param inputs The module&#39;s input variables, keyed by variable name.
         * 
         * @return builder
         * 
         */
        public Builder inputs(Map<String,Object> inputs) {
            return inputs(Output.of(inputs));
        }

        /**
         * @param source The module source address (a registry reference, URL, or local path).
         * 
         * @return builder
         * 
         */
        public Builder source(String source) {
            $.source = source;
            return this;
        }

        /**
         * @param version An optional version constraint, used when source is a registry module reference.
         * 
         * @return builder
         * 
         */
        public Builder version(@Nullable String version) {
            $.version = version;
            return this;
        }

        public ModuleArgs build() {
            if ($.source == null) {
                throw new MissingRequiredPropertyException("ModuleArgs", "source");
            }
            return $;
        }
    }

}
