// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.hcl;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.hcl.ModuleArgs;
import com.pulumi.hcl.Utilities;
import java.lang.Object;
import java.lang.String;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * A Terraform/OpenTofu module instantiated as a component resource.
 * 
 */
@ResourceType(type="hcl:index:Module")
public class Module extends com.pulumi.resources.ComponentResource {
    /**
     * The module&#39;s input variables, keyed by variable name.
     * 
     */
    @Export(name="inputs", refs={Map.class,String.class,Object.class}, tree="[0,1,2]")
    private Output</* @Nullable */ Map<String,Object>> inputs;

    /**
     * @return The module&#39;s input variables, keyed by variable name.
     * 
     */
    public Output<Optional<Map<String,Object>>> inputs() {
        return Codegen.optional(this.inputs);
    }
    /**
     * The module&#39;s output values, keyed by output name.
     * 
     */
    @Export(name="outputs", refs={Map.class,String.class,Object.class}, tree="[0,1,2]")
    private Output<Map<String,Object>> outputs;

    /**
     * @return The module&#39;s output values, keyed by output name.
     * 
     */
    public Output<Map<String,Object>> outputs() {
        return this.outputs;
    }
    /**
     * The module source address (a registry reference, URL, or local path).
     * 
     */
    @Export(name="source", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> source;

    /**
     * @return The module source address (a registry reference, URL, or local path).
     * 
     */
    public Output<Optional<String>> source() {
        return Codegen.optional(this.source);
    }
    /**
     * An optional version constraint, used when source is a registry module reference.
     * 
     */
    @Export(name="version", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> version;

    /**
     * @return An optional version constraint, used when source is a registry module reference.
     * 
     */
    public Output<Optional<String>> version() {
        return Codegen.optional(this.version);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Module(java.lang.String name) {
        this(name, ModuleArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Module(java.lang.String name, ModuleArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Module(java.lang.String name, ModuleArgs args, @Nullable com.pulumi.resources.ComponentResourceOptions options) {
        super("hcl:index:Module", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), true);
    }

    private static ModuleArgs makeArgs(ModuleArgs args, @Nullable com.pulumi.resources.ComponentResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ModuleArgs.Empty : args;
    }

    private static com.pulumi.resources.ComponentResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.ComponentResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.ComponentResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.ComponentResourceOptions.merge(defaultOptions, options, id);
    }

}
