// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A Terraform/OpenTofu module instantiated as a component resource.
 */
export class Module extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'hcl:index:Module';

    /**
     * Returns true if the given object is an instance of Module.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Module {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Module.__pulumiType;
    }

    /**
     * The module's input variables, keyed by variable name.
     */
    declare public readonly inputs: pulumi.Output<{[key: string]: any} | undefined>;
    /**
     * The module's output values, keyed by output name.
     */
    declare public /*out*/ readonly outputs: pulumi.Output<{[key: string]: any}>;
    /**
     * The module source address (a registry reference, URL, or local path).
     */
    declare public readonly source: pulumi.Output<string | undefined>;
    /**
     * An optional version constraint, used when source is a registry module reference.
     */
    declare public readonly version: pulumi.Output<string | undefined>;

    /**
     * Create a Module resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ModuleArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.source === undefined && !opts.urn) {
                throw new Error("Missing required property 'source'");
            }
            resourceInputs["inputs"] = args?.inputs;
            resourceInputs["source"] = args?.source;
            resourceInputs["version"] = args?.version;
            resourceInputs["outputs"] = undefined /*out*/;
        } else {
            resourceInputs["inputs"] = undefined /*out*/;
            resourceInputs["outputs"] = undefined /*out*/;
            resourceInputs["source"] = undefined /*out*/;
            resourceInputs["version"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Module.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a Module resource.
 */
export interface ModuleArgs {
    /**
     * The module's input variables, keyed by variable name.
     */
    inputs?: pulumi.Input<{[key: string]: any} | undefined>;
    /**
     * The module source address (a registry reference, URL, or local path).
     */
    source: string;
    /**
     * An optional version constraint, used when source is a registry module reference.
     */
    version?: string;
}
